/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2016 (13.0.4001)
    Source Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2016
    Target Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Target Database Engine Type : Standalone SQL Server
*/

USE [master]
GO

/****** Object:  Database [HedgehogManager]    Script Date: 2019-03-08 4:06:51 PM ******/
CREATE DATABASE [HedgehogManager]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HedgehogManager', FILENAME = N'H:\MSSQL\DATA\HedgehogManager.mdf' , SIZE = 102400KB , MAXSIZE = UNLIMITED, FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N'HedgehogManager_log', FILENAME = N'I:\MSSQL\DATA\HedgehogManager_log.ldf' , SIZE = 51200KB , MAXSIZE = 2048GB , FILEGROWTH = 25600KB )
GO

ALTER DATABASE [HedgehogManager] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HedgehogManager].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HedgehogManager] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HedgehogManager] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HedgehogManager] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HedgehogManager] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HedgehogManager] SET ARITHABORT OFF 
GO

ALTER DATABASE [HedgehogManager] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HedgehogManager] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HedgehogManager] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HedgehogManager] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HedgehogManager] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HedgehogManager] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HedgehogManager] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HedgehogManager] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HedgehogManager] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HedgehogManager] SET  ENABLE_BROKER 
GO

ALTER DATABASE [HedgehogManager] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HedgehogManager] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HedgehogManager] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HedgehogManager] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HedgehogManager] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HedgehogManager] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HedgehogManager] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HedgehogManager] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HedgehogManager] SET  MULTI_USER 
GO

ALTER DATABASE [HedgehogManager] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HedgehogManager] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HedgehogManager] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HedgehogManager] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HedgehogManager] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HedgehogManager] SET QUERY_STORE = OFF
GO

USE [HedgehogManager]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [HedgehogManager] SET  READ_WRITE 
GO


